// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Caml_module = require("bs-platform/lib/js/caml_module.js");

var MeshBuilder = Caml_module.init_mod([
      "babylonjs.ml",
      168,
      6
    ], {
      TAG: /* Module */0,
      _0: [
        [
          {
            TAG: /* Module */0,
            _0: []
          },
          "Sphere"
        ],
        [
          {
            TAG: /* Module */0,
            _0: []
          },
          "Lines"
        ],
        [
          {
            TAG: /* Module */0,
            _0: []
          },
          "Plane"
        ]
      ]
    });

Caml_module.update_mod({
      TAG: /* Module */0,
      _0: [
        [
          {
            TAG: /* Module */0,
            _0: []
          },
          "Sphere"
        ],
        [
          {
            TAG: /* Module */0,
            _0: []
          },
          "Lines"
        ],
        [
          {
            TAG: /* Module */0,
            _0: []
          },
          "Plane"
        ]
      ]
    }, MeshBuilder, MeshBuilder);

var Vector3;

var Color3;

var Engine;

var Scene;

var FreeCamera;

var DeviceOrientationCamera;

var DynamicTexture;

var HemisphericLight;

var StandardMaterial;

exports.Vector3 = Vector3;
exports.Color3 = Color3;
exports.Engine = Engine;
exports.Scene = Scene;
exports.FreeCamera = FreeCamera;
exports.DeviceOrientationCamera = DeviceOrientationCamera;
exports.DynamicTexture = DynamicTexture;
exports.HemisphericLight = HemisphericLight;
exports.StandardMaterial = StandardMaterial;
exports.MeshBuilder = MeshBuilder;
/* MeshBuilder Not a pure module */
